In [1]:
import duckdb
import pandas as pd
import requests
import json
from datetime import datetime, timedelta
import os
from pathlib import Path
import geopandas as gpd
import xml.etree.ElementTree as ET
import re

In [16]:
tree = ET.parse('RSS.xml')
root = tree.getroot()

print(tree)
items = []
for item in root.findall('./channel/item'):
    title = item.find('title').text.strip() if item.find('title') is not None else ""
    link = item.find('link').text.strip() if item.find('link') is not None else ""
    pub_date_raw = item.find('pubDate').text.strip() if item.find('pubDate') is not None else ""
    
    # Convertir fecha de publicación
    try:
        pub_date = datetime.strptime(pub_date_raw, "%a, %d %b %Y %H:%M:%S %Z")
    except ValueError:
        pub_date = None

    filename = link.split('/')[-1]
    lower_link = link.lower()
    lower_filename = filename.lower()

    # --- Lógica de Extracción de Metadatos ---

    # A) Categoría Principal (estudios_completos, estudios_basicos, etc.)
    main_category = "Otros"
    if "estudios_completos" in lower_link:
        main_category = "Estudios Completos"
    elif "estudios_basicos" in lower_link:
        main_category = "Estudios Basicos"
    elif "estudios_rutas" in lower_link:
        main_category = "Estudios de Rutas"
    elif "zonificacion" in lower_link:
        main_category = "Zonificacion"

    # B) Tipo de Estudio (viajes, etapas, etc.)
    study_type = "Desconocido"
    if "viajes" in lower_filename:
        study_type = "Viajes"
    elif "etapas" in lower_filename:
        if "_c" in lower_filename or "carretera" in lower_link:
            study_type = "Etapas (Carretera)"
        else:
            study_type = "Etapas"
    elif "pernoctaciones" in lower_filename:
        study_type = "Pernoctaciones"
    elif "personas" in lower_filename:
        study_type = "Personas"
    elif "frecuencia" in lower_link or "frecuencia" in lower_filename:
        study_type = "Frecuencia"
    elif "calidad" in lower_link or "descartados" in lower_filename:
        study_type = "Calidad"
    elif "od_rutas" in lower_filename:
        study_type = "Matriz OD Rutas"
    elif "relaciones_tramos" in lower_filename:
        study_type = "Relaciones Tramos-Rutas"
    elif "tramos_info" in lower_filename:
        study_type = "Info Tramos OD"
    elif "zonificacion" in lower_link:
        study_type = "Geometria/Zonificacion"
    elif "agregados" in lower_filename:
        study_type = "Datos Agregados"

    # C) Zona (municipios, distritos, GAU)
    zone_type = "N/A" # Por defecto
    if "municipios" in lower_link or "municipios" in lower_filename:
        zone_type = "Municipios"
    elif "distritos" in lower_link or "distritos" in lower_filename:
        zone_type = "Distritos"
    elif "gau" in lower_link or "gau" in lower_filename:
        zone_type = "GAU"
    elif "rutas" in lower_link:
        zone_type = "Rutas"
    
    # D) Extracción de Fecha (YYYY, MM, DD) desde el nombre del archivo
    # Buscamos patrones como 20240101 (diario) o 202401 (mensual)
    year, month, day = None, None, None
    
    # Regex para YYYYMMDD
    date_match_daily = re.search(r'(\d{4})(\d{2})(\d{2})', filename)
    # Regex para YYYYMM (archivos mensuales o tar)
    date_match_monthly = re.search(r'(\d{4})(\d{2})', filename)
    
    if date_match_daily:
        year = int(date_match_daily.group(1))
        month = int(date_match_daily.group(2))
        day = int(date_match_daily.group(3))
    elif date_match_monthly:
        year = int(date_match_monthly.group(1))
        month = int(date_match_monthly.group(2))
        # day se queda como None para mensuales

    items.append({
        "main_category": main_category, # Nueva columna solicitada
        "study_type": study_type,
        "zone_type": zone_type,
        "year": year,
        "month": month,
        "day": day,
        "publication_date": pub_date,
        "filename": filename,
        "source_url": link
    })
df_catalog = pd.DataFrame(items)

<xml.etree.ElementTree.ElementTree object at 0x7750480e7800>

In [2]:
import duckdb
import pandas as pd
import requests
import json
from datetime import datetime, timedelta
import os
from pathlib import Path
import geopandas as gpd
import xml.etree.ElementTree as ET
import re
from pathlib import Path

In [3]:
con = duckdb.connect()
con.sql("INSTALL ducklake; LOAD ducklake;")
con.sql("INSTALL spatial; LOAD spatial;")

In [4]:
# This for Detaching from ducklake in case
con.sql(f"""
USE memory;
DETACH my_ducklake;
    """)

BinderException: Binder Error: Failed to detach database with name "my_ducklake": database not found

In [5]:
# Ataching to local duck lake
con.sql(f"""
ATTACH 'ducklake:my_ducklake.ducklake' AS my_ducklake;

USE my_ducklake;
    """)

In [5]:
con.sql("CREATE SCHEMA IF NOT EXISTS bronze")

In [21]:
# Inserting the catalog from where we will get the urls for the data
con.sql("CREATE OR REPLACE TABLE bronze.catalog AS SELECT * FROM df_catalog")

In [7]:
files_df = con.sql("""
    SELECT *
    FROM bronze.catalog 
   
""").df()
files_df

,main_category,study_type,zone_type,year,month,day,publication_date,filename,source_url
0,Estudios Completos,Viajes,N/A,2023.0,12.0,17.0,2025-11-18 12:15:51,20231217_viajes.csv.gz,https://movilidad-opendata.mitma.es/estudios_c...
1,Estudios Completos,Viajes,N/A,2023.0,12.0,16.0,2025-11-18 12:15:50,20231216_viajes.csv.gz,https://movilidad-opendata.mitma.es/estudios_c...
2,Estudios Completos,Viajes,N/A,2023.0,12.0,13.0,2025-11-18 12:15:46,20231213_viajes.csv.gz,https://movilidad-opendata.mitma.es/estudios_c...
3,Estudios Completos,Viajes,N/A,2023.0,12.0,14.0,2025-11-18 12:15:46,20231214_viajes.csv.gz,https://movilidad-opendata.mitma.es/estudios_c...
4,Estudios Completos,Viajes,N/A,2023.0,12.0,15.0,2025-11-18 12:15:46,20231215_viajes.csv.gz,https://movilidad-opendata.mitma.es/estudios_c...
...,...,...,...,...,...,...,...,...,...
13378,Estudios Basicos,Desconocido,Distritos,NaN,NaN,NaN,2022-12-20 15:07:40,,https://movilidad-opendata.mitma.es/estudios_b...
13379,Estudios Basicos,Calidad,N/A,NaN,NaN,NaN,2022-12-20 15:00:05,,https://movilidad-opendata.mitma.es/estudios_b...
13380,Estudios Basicos,Calidad,N/A,NaN,NaN,NaN,2022-12-20 14:59:42,,https://movilidad-opendata.mitma.es/estudios_b...
13381,Estudios Basicos,Desconocido,N/A,NaN,NaN,NaN,2022-12-20 14:59:32,,https://movilidad-opendata.mitma.es/estudios_b...
13382,Otros,Desconocido,N/A,2020.0,12.0,3.0,2022-12-19 13:32:07,LICENCIA de datos abiertos del MITMA 20201203.pdf,https://movilidad-opendata.mitma.es/LICENCIA d...

In [23]:
con.sql("""
    SELECT * FROM bronze.trips WHERE part_month = '2'
""")

┌──────────┬─────────┬───────────┬────────────────┬──────────┬─────────────────┬──────────────────────┬──────────────────┬───────────────────────┬───────────┬─────────┬─────────┬─────────┬─────────┬───────────────────────┬───────────┬────────────┬───────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│   date   │ period  │ id_origin │ id_destination │ distance │ activity_origin │ activity_destination │ study_origin_pos │ study_destination_pos │ residence │  rent   │   age   │   sex   │ n_trips │ trips_total_length_km │ part_year │ part_month │ zone_type │ source  │                                                             source_url                                                              │       ingestion_date       │
│ varchar  │ varchar │  varchar  │    varchar     │ varchar  │     varchar     │       varchar        │     varchar      │        varchar        │  varchar  │ varchar │ varchar │ varchar │ varchar │        varchar        │  varchar  │  varchar   │  varchar  │ varchar │                                                               varchar                                                               │         timestamp          │
├──────────┼─────────┼───────────┼────────────────┼──────────┼─────────────────┼──────────────────────┼──────────────────┼───────────────────────┼───────────┼─────────┼─────────┼─────────┼─────────┼───────────────────────┼───────────┼────────────┼───────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 20230228 │ 06      │ 01009_AM  │ 01001          │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.901   │ 3.018                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 09      │ 01009_AM  │ 01001          │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.311   │ 2.609                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 19      │ 01009_AM  │ 01001          │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.311   │ 2.609                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 22      │ 01009_AM  │ 01001          │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.491   │ 3.114                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 21      │ 01002     │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.491   │ 115.606               │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 08      │ 01009_AM  │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.901   │ 29.975                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 11      │ 01009_AM  │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 3.155   │ 37.143                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 14      │ 01009_AM  │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 3.155   │ 48.099                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 19      │ 01009_AM  │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.901   │ 45.975                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 17      │ 01017_AM  │ 01001          │ 10-50    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.491   │ 26.409                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│    ·     │ ·       │    ·      │   ·            │   ·      │     ·           │  ·                   │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │   ·     │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│    ·     │ ·       │    ·      │   ·            │   ·      │     ·           │  ·                   │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │   ·     │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│    ·     │ ·       │    ·      │   ·            │   ·      │     ·           │  ·                   │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │   ·     │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│ 20230228 │ 06      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 3.917   │ 2.822                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 07      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 3.917   │ 3.558                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 07      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 37.07   │ 47.305                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 08      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 11.751  │ 14.264                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 08      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 6.74    │ 5.65                  │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 09      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 3.917   │ 2.994                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 09      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 16.85   │ 16.766                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 10      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 27.419  │ 31.344                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 10      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 20.22   │ 23.735                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
│ 20230228 │ 11      │ 0105903   │ 0105904        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 50.921  │ 55.531                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz │ 2025-11-28 13:42:15.932201 │
├──────────┴─────────┴───────────┴────────────────┴──────────┴─────────────────┴──────────────────────┴──────────────────┴───────────────────────┴───────────┴─────────┴─────────┴─────────┴─────────┴───────────────────────┴───────────┴────────────┴───────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                     21 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [24]:
duckdb.sql(f"""
   FROM glob('my_ducklake.ducklake.files/**/*');
    FROM 'my_ducklake.ducklake.files/**/*.parquet' LIMIT 10;    
    """)

┌──────────┬──────────────────────┬───────────┬─────────┬──────────────────────┬──────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────┐

In [25]:
con.sql("""
    SELECT * FROM bronze.catalog
""")

┌────────────────────┬────────────┬───────────┬────────┬────────┬────────┬─────────────────────┬────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│   main_category    │ study_type │ zone_type │  year  │ month  │  day   │  publication_date   │                filename                │                                                                 source_url                                                                  │
│      varchar       │  varchar   │  varchar  │ double │ double │ double │    timestamp_ns     │                varchar                 │                                                                   varchar                                                                   │
├────────────────────┼────────────┼───────────┼────────┼────────┼────────┼─────────────────────┼────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   17.0 │ 2025-11-18 12:15:51 │ 20231217_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231217_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   16.0 │ 2025-11-18 12:15:50 │ 20231216_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231216_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   13.0 │ 2025-11-18 12:15:46 │ 20231213_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231213_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   14.0 │ 2025-11-18 12:15:46 │ 20231214_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231214_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   15.0 │ 2025-11-18 12:15:46 │ 20231215_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231215_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   11.0 │ 2025-11-18 12:15:45 │ 20231211_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231211_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   12.0 │   12.0 │ 2025-11-18 12:15:45 │ 20231212_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231212_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   11.0 │   26.0 │ 2025-11-18 12:15:44 │ 20231126_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231126_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   11.0 │   24.0 │ 2025-11-18 12:15:43 │ 20231124_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231124_viajes.csv.gz                              │
│ Estudios Completos │ Viajes     │ N/A       │ 2023.0 │   11.0 │   22.0 │ 2025-11-18 12:15:42 │ 20231122_viajes.csv.gz                 │ https://movilidad-opendata.mitma.es/estudios_completos/tiempos de viaje/viajes_duracion/20231122_viajes.csv.gz                              │
│        ·           │   ·        │  ·        │    ·   │     ·  │     ·  │          ·          │           ·                            │                                                       ·                                                                                     │
│        ·           │   ·        │  ·        │    ·   │     ·  │     ·  │          ·          │           ·                            │                                                       ·                                                                                     │
│        ·           │   ·        │  ·        │    ·   │     ·  │     ·  │          ·          │           ·                            │                                                       ·                                                                                     │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   22.0 │ 2023-04-13 07:32:58 │ 20230322_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230322_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   23.0 │ 2023-04-13 07:32:58 │ 20230323_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230323_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   18.0 │ 2023-04-13 07:32:57 │ 20230318_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230318_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   19.0 │ 2023-04-13 07:32:57 │ 20230319_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230319_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   20.0 │ 2023-04-13 07:32:57 │ 20230320_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230320_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   16.0 │ 2023-04-13 07:32:56 │ 20230316_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230316_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   17.0 │ 2023-04-13 07:32:56 │ 20230317_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230317_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   14.0 │ 2023-04-13 07:32:55 │ 20230314_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230314_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   15.0 │ 2023-04-13 07:32:55 │ 20230315_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230315_Personas_dia_distritos.csv.gz │
│ Estudios Basicos   │ Personas   │ Distritos │ 2023.0 │    3.0 │   11.0 │ 2023-04-13 07:32:54 │ 20230311_Personas_dia_distritos.csv.gz │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/personas/ficheros-diarios/2023-03/20230311_Personas_dia_distritos.csv.gz │
├────────────────────┴────────────┴───────────┴────────┴────────┴────────┴─────────────────────┴────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                             9 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [27]:
# TABLA viajes Bronze 
con.sql("""
    CREATE OR REPLACE TABLE bronze.trips (
        date VARCHAR,
        period VARCHAR,
        id_origin VARCHAR,
        id_destination VARCHAR,
        distance VARCHAR,
        activity_origin VARCHAR,
        activity_destination VARCHAR,
        study_origin_pos VARCHAR,
        study_destination_pos VARCHAR,
        residence VARCHAR,
        rent VARCHAR,
        age VARCHAR,
        sex VARCHAR,
        n_trips VARCHAR,
        trips_total_length_km VARCHAR,
        
        part_year VARCHAR,
        part_month VARCHAR,
        zone_type VARCHAR,
        source VARCHAR,
        source_url VARCHAR,
        ingestion_date TIMESTAMP
    );
""")
# con.sql("ALTER TABLE bronze.trips SET PARTITIONED BY (zone_type, source, part_year, part_month)")

In [28]:
# Funcion para ingerir datos viajes

def cargar_viajes_por_criterio(con, year, month, zone_type):
    # zone_type format : 'Municipio' 'Distritos' 'GAUS'

    # saca urls del catalogo
    files_df = con.sql(f"""
        SELECT source_url 
        FROM bronze.catalog 
        WHERE year = {year}
        AND month = {month}
        AND zone_type = '{zone_type}'
        AND main_category = 'Estudios Basicos'
        AND study_type = 'Viajes'
        AND filename LIKE '%.csv.gz'
    """).df()

    urls = files_df['source_url'].tolist()
    print(urls)
    #Insertar a la tabla 
    con.sql(f"""INSERT INTO bronze.trips
            SELECT 
                        -- 1. Transformación de Fecha (Corrección del VARCHAR '20230131')
                        fecha as date,
                        periodo as period,
                        origen as id_origin,
                        destino as id_destination ,
                        distancia as distance,
                        actividad_origen as activity_origin,
                        actividad_destino as activity_destination,
                        estudio_origen_posible as study_origin_pos,
                        estudio_destino_posible as study_destination_pos,
                        residencia as residence,
                        renta as rent,
                        edad as age,
                        sexo as sex,
                        viajes as n_trips,
                        viajes_km as trips_total_length_km,
                        -- 2. Metadatos (Tus columnas personalizadas)
                        {year} as part_year,
                        {month} as part_month,
                        '{zone_type}' as zone_type,  -- Valor fijo pasado por parámetro
                        'MITMA' as source,
                        filename as source_url,      -- Columna mágica generada por read_csv(..., filename=True)
                        current_timestamp as ingestion_date
                        
                    FROM read_csv(
                        {urls[:7]}, 
                        delim='|', 
                        header=True, 
                        filename=True,
                        union_by_name=True,
                        null_padding=True,
                        ignore_errors=True,
                        all_varchar=True -- Leemos todo como texto para evitar fallos de tipo antes de castear
                    )""")

In [29]:
cargar_viajes_por_criterio(con, 2023, 2, "Distritos")

['https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230228_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230227_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230226_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230225_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230224_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230223_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230222_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230221_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230220_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230219_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230218_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230217_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230216_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230215_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230214_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230213_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230212_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230211_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230210_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230208_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230207_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230206_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230205_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230204_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230203_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230202_Viajes_distritos.csv.gz', 'https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz']

RuntimeError: Query interrupted

In [7]:

con.sql("""
    SELECT * FROM bronze.trips  WHERE date = '20230201' -- and period = '08' and activity_origin = 'trabajo_estudio' and id_origin = '0105903' and id_destination = '0105901'
       -- and sex = 'mujer'
    ORDER BY trips_total_length_km ASC

""")

┌──────────┬─────────┬───────────┬────────────────┬──────────┬─────────────────┬──────────────────────┬──────────────────┬───────────────────────┬───────────┬─────────┬─────────┬─────────┬─────────┬───────────────────────┬───────────┬────────────┬───────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│   date   │ period  │ id_origin │ id_destination │ distance │ activity_origin │ activity_destination │ study_origin_pos │ study_destination_pos │ residence │  rent   │   age   │   sex   │ n_trips │ trips_total_length_km │ part_year │ part_month │ zone_type │ source  │                                                             source_url                                                              │       ingestion_date       │
│ varchar  │ varchar │  varchar  │    varchar     │ varchar  │     varchar     │       varchar        │     varchar      │        varchar        │  varchar  │ varchar │ varchar │ varchar │ varchar │        varchar        │  varchar  │  varchar   │  varchar  │ varchar │                                                               varchar                                                               │         timestamp          │
├──────────┼─────────┼───────────┼────────────────┼──────────┼─────────────────┼──────────────────────┼──────────────────┼───────────────────────┼───────────┼─────────┼─────────┼─────────┼─────────┼───────────────────────┼───────────┼────────────┼───────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 20230201 │ 14      │ 29017     │ 29017          │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ NA      │ NA      │ 1.0     │ 0.500787401575        │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 11      │ 0704004   │ 0704001        │ 0.5-2    │ no_frecuente    │ frecuente            │ no               │ no                    │ 07        │ 10-15   │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 14      │ 2800502   │ 2800502        │ 0.5-2    │ trabajo_estudio │ no_frecuente         │ no               │ no                    │ 19        │ 10-15   │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 07      │ 2807901   │ 2807901        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 00      │ 2807901   │ 2807901        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 20      │ 0801905   │ 0801902        │ 0.5-2    │ no_frecuente    │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 45-65   │ mujer   │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 02      │ 2807901   │ 2807901        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 14      │ 2800502   │ 2800502        │ 0.5-2    │ no_frecuente    │ trabajo_estudio      │ no               │ no                    │ 19        │ 10-15   │ NA      │ NA      │ 1.0     │ 0.501                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 16      │ 4718603   │ 4718605        │ 0.5-2    │ trabajo_estudio │ frecuente            │ no               │ no                    │ 47        │ >15     │ NA      │ NA      │ 1.0     │ 0.501538461538        │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 09      │ 4718603   │ 4718605        │ 0.5-2    │ trabajo_estudio │ frecuente            │ no               │ no                    │ 47        │ >15     │ NA      │ NA      │ 1.0     │ 0.501538461538        │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│    ·     │ ·       │    ·      │    ·           │   ·      │  ·              │     ·                │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │  ·      │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│    ·     │ ·       │    ·      │    ·           │   ·      │  ·              │     ·                │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │  ·      │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│    ·     │ ·       │    ·      │    ·           │   ·      │  ·              │     ·                │ ·                │ ·                     │ ·         │  ·      │ ·       │ ·       │  ·      │   ·                   │  ·        │ ·          │     ·     │   ·     │                                                                  ·                                                                  │             ·              │
│ 20230201 │ 09      │ 0827901   │ 0827904        │ 0.5-2    │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ >15     │ 45-65   │ hombre  │ 1.823   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 21      │ 08005     │ 08086          │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 08        │ 10-15   │ 25-45   │ hombre  │ 1.296   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 11      │ 0301406   │ 0312203        │ 0.5-2    │ frecuente       │ casa                 │ no               │ no                    │ 03        │ 10-15   │ 65-100  │ NA      │ 1.434   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 11      │ 2906701   │ 2906705        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ 65-100  │ hombre  │ 1.627   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 23      │ 30005     │ 30005          │ 0.5-2    │ no_frecuente    │ frecuente            │ no               │ no                    │ 30        │ 10-15   │ 65-100  │ hombre  │ 1.741   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 09      │ 46135     │ 46135          │ 0.5-2    │ trabajo_estudio │ casa                 │ no               │ no                    │ 46        │ 10-15   │ 45-65   │ NA      │ 1.514   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 13      │ 3727401   │ 3727401        │ 0.5-2    │ no_frecuente    │ frecuente            │ no               │ no                    │ 37        │ >15     │ 45-65   │ NA      │ 1.522   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 19      │ 0105906   │ 0105906        │ 0.5-2    │ casa            │ frecuente            │ no               │ si                    │ 01        │ >15     │ NA      │ NA      │ 1.763   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 12      │ 2906705   │ 2906701        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 29        │ <10     │ 65-100  │ hombre  │ 1.627   │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230201 │ 12      │ 0301408   │ 0301407        │ 0.5-2    │ frecuente       │ frecuente            │ no               │ no                    │ 03        │ <10     │ NA      │ NA      │ 1.0     │ 0.948                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230201_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
├──────────┴─────────┴───────────┴────────────────┴──────────┴─────────────────┴──────────────────────┴──────────────────┴───────────────────────┴───────────┴─────────┴─────────┴─────────┴─────────┴───────────────────────┴───────────┴────────────┴───────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                                                                                                                                                                                                                                                                                     21 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [10]:
con.sql("""
    SELECT * FROM bronze.trips WHERE  CAST(n_trips as INTEGER) > 1  and id_origin =  '0801504'  and id_destination ='FRJ15' and age = '0-25' and sex = 'mujer'
        ORDER BY trips_total_length_km DESC

""")

┌──────────┬─────────┬───────────┬────────────────┬──────────┬─────────────────┬──────────────────────┬──────────────────┬───────────────────────┬───────────┬─────────┬─────────┬─────────┬─────────┬───────────────────────┬───────────┬────────────┬───────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│   date   │ period  │ id_origin │ id_destination │ distance │ activity_origin │ activity_destination │ study_origin_pos │ study_destination_pos │ residence │  rent   │   age   │   sex   │ n_trips │ trips_total_length_km │ part_year │ part_month │ zone_type │ source  │                                                             source_url                                                              │       ingestion_date       │
│ varchar  │ varchar │  varchar  │    varchar     │ varchar  │     varchar     │       varchar        │     varchar      │        varchar        │  varchar  │ varchar │ varchar │ varchar │ varchar │        varchar        │  varchar  │  varchar   │  varchar  │ varchar │                                                               varchar                                                               │         timestamp          │
├──────────┼─────────┼───────────┼────────────────┼──────────┼─────────────────┼──────────────────────┼──────────────────┼───────────────────────┼───────────┼─────────┼─────────┼─────────┼─────────┼───────────────────────┼───────────┼────────────┼───────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 20230211 │ 07      │ 0801504   │ FRJ15          │ >50      │ trabajo_estudio │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.217   │ 999.946               │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230211_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230126 │ 10      │ 0801504   │ FRJ15          │ >50      │ no_frecuente    │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 6.866   │ 839.906               │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230126_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230103 │ 08      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.044   │ 835.586               │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230103_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230125 │ 20      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.296   │ 835.362               │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230125_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230107 │ 10      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.276   │ 826.02                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230107_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230227 │ 08      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 7.861   │ 818.127               │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230227_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230113 │ 08      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ >15     │ 0-25    │ mujer   │ 6.585   │ 803.4                 │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230113_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230126 │ 05      │ 0801504   │ FRJ15          │ >50      │ no_frecuente    │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 6.182   │ 758.305               │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230126_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230221 │ 18      │ 0801504   │ FRJ15          │ >50      │ frecuente       │ no_frecuente         │ no               │ no                    │ 25        │ 10-15   │ 0-25    │ mujer   │ 15.277  │ 1862.479              │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230221_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230117 │ 18      │ 0801504   │ FRJ15          │ >50      │ frecuente       │ no_frecuente         │ no               │ no                    │ 25        │ 10-15   │ 0-25    │ mujer   │ 14.218  │ 1739.585              │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230117_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230219 │ 06      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.417   │ 1026.185              │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230219_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230210 │ 17      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.296   │ 1015.902              │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230210_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230210 │ 21      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.296   │ 1012.587              │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230210_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230225 │ 08      │ 0801504   │ FRJ15          │ >50      │ casa            │ no_frecuente         │ no               │ no                    │ 08        │ 10-15   │ 0-25    │ mujer   │ 8.158   │ 1001.608              │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230225_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
├──────────┴─────────┴───────────┴────────────────┴──────────┴─────────────────┴──────────────────────┴──────────────────┴───────────────────────┴───────────┴─────────┴─────────┴─────────┴─────────┴───────────────────────┴───────────┴────────────┴───────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ 14 rows                                                                                                                                                                                                                                                                                                                                                                                                                           21 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [77]:
con.sql("""
    SELECT * FROM bronze.trips WHERE date = '20230209' and part_month = '2' and id_origin = '0105903' and period = '08'and id_destination = '0105901' and activity_origin = 'casa' and distance = '0.5-2' and activity_destination = 'trabajo_estudio'
    ORDER BY sex  DESC
""")

┌──────────┬─────────┬───────────┬────────────────┬──────────┬─────────────────┬──────────────────────┬──────────────────┬───────────────────────┬───────────┬─────────┬─────────┬─────────┬─────────┬───────────────────────┬───────────┬────────────┬───────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│   date   │ period  │ id_origin │ id_destination │ distance │ activity_origin │ activity_destination │ study_origin_pos │ study_destination_pos │ residence │  rent   │   age   │   sex   │ n_trips │ trips_total_length_km │ part_year │ part_month │ zone_type │ source  │                                                             source_url                                                              │       ingestion_date       │
│ varchar  │ varchar │  varchar  │    varchar     │ varchar  │     varchar     │       varchar        │     varchar      │        varchar        │  varchar  │ varchar │ varchar │ varchar │ varchar │        varchar        │  varchar  │  varchar   │  varchar  │ varchar │                                                               varchar                                                               │         timestamp          │
├──────────┼─────────┼───────────┼────────────────┼──────────┼─────────────────┼──────────────────────┼──────────────────┼───────────────────────┼───────────┼─────────┼─────────┼─────────┼─────────┼───────────────────────┼───────────┼────────────┼───────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 0-25    │ mujer   │ 29.91   │ 29.197                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ si                    │ 01        │ >15     │ 0-25    │ mujer   │ 14.955  │ 18.114                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 65-100  │ mujer   │ 15.088  │ 16.628                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 45-65   │ mujer   │ 47.745  │ 53.529                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 25-45   │ mujer   │ 49.725  │ 58.424                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 0-25    │ hombre  │ 25.665  │ 32.677                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 25-45   │ hombre  │ 28.296  │ 35.255                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ si                    │ 01        │ >15     │ 0-25    │ hombre  │ 5.133   │ 8.962                 │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 39.704  │ 55.055                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
│ 20230209 │ 08      │ 0105903   │ 0105901        │ 0.5-2    │ casa            │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 65-100  │ hombre  │ 11.16   │ 15.436                │ 2023      │ 2          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-02/20230209_Viajes_distritos.csv.gz │ 2025-11-26 17:11:32.743017 │
├──────────┴─────────┴───────────┴────────────────┴──────────┴─────────────────┴──────────────────────┴──────────────────┴───────────────────────┴───────────┴─────────┴─────────┴─────────┴─────────┴───────────────────────┴───────────┴────────────┴───────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                           21 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [96]:
def cargar_info_zona(con,zone_type):
    # zone_type = 'municipios','distritos','gaus'
    #Find in catalog zone type files
    zone_dic = {"municipios":"municiples","distritos":"districts","gaus":"GAUS"}
    # Crea tabla de info sobre las zonas
    con.sql(f"""
    CREATE OR REPLACE TABLE bronze.{zone_dic[zone_type]}_info (
        id_{zone_dic[zone_type]} VARCHAR,
        name_{zone_dic[zone_type]} VARCHAR,
        zone_type VARCHAR,
        source VARCHAR,
        source_url VARCHAR,
        ingestion_date TIMESTAMP,
        geometry GEOMETRY ,
        centroid GEOMETRY ,
            );
        """)
    con.sql(f"ALTER TABLE bronze.{zone_dic[zone_type]}_info SET PARTITIONED BY (zone_type)")
    
    file_info = con.sql(f"""
    SELECT source_url, filename 
    FROM bronze.catalog 
    WHERE (main_category = 'Zonificacion' OR main_category = 'Otros')
      AND (filename ILIKE '%{zone_type}%') 
      AND (filename ILIKE '%.shp' OR filename ILIKE '%.shx' OR filename ILIKE '%.dbf' OR filename ILIKE '%.prj' OR filename ILIKE '%.csv')
      --AND filename NOT ILIKE '%centroides%'
        """).df()
    print(len(file_info))
    #temp dowload data
    urls = file_info["source_url"]
    os.makedirs(f"temp_downloads/{zone_type}", exist_ok=True)
    for key, url in urls.items():
        filename = url.split('/')[-1]
        path = f"temp_downloads/{zone_type}/{filename}"
        # Descargamos solo si no existe para ahorrar tiempo
        if not os.path.exists(path):
            print(f"Descargando {filename}...")
            r = requests.get(url)
            with open(path, 'wb') as f:
                f.write(r.content)




    shp_path = f"temp_downloads/{zone_type}/zonificacion_{zone_type}.shp"
    shp_centroid_path = f"temp_downloads/{zone_type}/zonificacion_{zone_type}_centroides.shp"
    csv_path = f"temp_downloads/{zone_type}/nombres_{zone_type}.csv"
    output_parquet = f"datalake/bronze/zonificacion/{zone_dic[zone_type]}.parquet"
    os.makedirs("datalake/bronze/zonificacion", exist_ok=True)
    #Join tables into zonetype info table
    
    con.sql(f"""
            INSERT INTO bronze.{zone_dic[zone_type]}_info
                SELECT 
                    -- IDs y Nombres (Usamos el diccionario para acertar el nombre de columna)
                    CAST(t1.ID AS VARCHAR) as id_{zone_dic[zone_type]},
                    t2.name as name_{zone_dic[zone_type]},
                    
                    -- Geometría (Se guardará como binario WKB automáticamente)

                    '{zone_dic[zone_type]}' as zone_type,
                    'MITMA' as source,
                    '{urls}' as source_url,      -- Columna mágica generada por read_csv(..., filename=True)
                    current_timestamp as ingestion_date,
                    t1.geom as geometry,
                    t3.geom as centroid
                FROM st_read('{shp_path}') t1
                -- Left Join con el CSV de nombres
                LEFT JOIN read_csv('{csv_path}', delim='|', header=True, auto_detect=True,filename=True) t2 
                ON CAST(t1.ID AS VARCHAR) = CAST(t2.ID AS VARCHAR)
                LEFT JOIN st_read('{shp_centroid_path}') t3 ON CAST(t1.ID AS VARCHAR) = CAST(t3.ID AS VARCHAR)
            
           """)

In [97]:
cargar_info_zona(con,"gaus")
cargar_info_zona(con,"municipios")
cargar_info_zona(con,"distritos")

10
10
10

In [98]:
con.sql("SELECT * FROM bronze.districts_info ")

┌──────────────┬──────────────────────┬───────────┬─────────┬──────────────────────┬──────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────┐

In [ ]:
con.sql("DROP TABLE bronze.GAUS_info ")
con.sql("DROP TABLE bronze.municiples_info ")
con.sql("DROP TABLE bronze.districts_info ")

In [ ]:
con.sql("SELECT * FROM bronze.districts_info WHERE name_districts LIKE '%Ali%'").df()

,id_districts,name_districts,zone_type,source,source_url,ingestion_date,geometry,centroid
0,0301401,Alicante/Alacant distrito 01,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 157, 99, 47, 73, 135,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
1,0301402,Alicante/Alacant distrito 02,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 233, 133, 47, 73, 215...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
2,0301403,Alicante/Alacant distrito 03,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 97, 178, 47, 73, 172,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
3,0301404,Alicante/Alacant distrito 04,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[5, 4, 0, 0, 0, 0, 0, 0, 125, 161, 46, 73, 108...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
4,0301405,Alicante/Alacant distrito 05,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 243, 87, 47, 73, 182,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
5,0301406,Alicante/Alacant distrito 06,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 216, 180, 46, 73, 183...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
6,0301407,Alicante/Alacant distrito 07,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[2, 4, 0, 0, 0, 0, 0, 0, 217, 146, 46, 73, 205...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."
7,0301408,Alicante/Alacant distrito 08,districts,MITMA,0 https://movilidad-opendata.mitma.es/zonif...,2025-11-28 14:44:55.510999,"[5, 4, 0, 0, 0, 0, 0, 0, 73, 10, 44, 73, 252, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..."

In [ ]:
con.sql("SELECT * FROM __ducklake_metadata_my_ducklake.ducklake_data_file")

┌──────────────┬──────────┬────────────────┬──────────────┬────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┬─────────────┬──────────────┬─────────────────┬─────────────┬──────────────┬──────────────┬────────────────┬───────────────────┬────────────┐
│ data_file_id │ table_id │ begin_snapshot │ end_snapshot │ file_order │                                                        path                                                         │ path_is_relative │ file_format │ record_count │ file_size_bytes │ footer_size │ row_id_start │ partition_id │ encryption_key │ partial_file_info │ mapping_id │
│    int64     │  int64   │     int64      │    int64     │   int64    │                                                       varchar                                                       │     boolean      │   varchar   │    int64     │      int64      │    int64    │    int64     │    int64     │    varchar     │      varchar      │   int64    │
├──────────────┼──────────┼────────────────┼──────────────┼────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┼─────────────┼──────────────┼─────────────────┼─────────────┼──────────────┼──────────────┼────────────────┼───────────────────┼────────────┤
│            0 │        2 │              2 │          191 │       NULL │ ducklake-019abd54-6408-77c2-a53a-7e376888c47d.parquet                                                               │ true             │ parquet     │        13383 │          290393 │        1526 │            0 │         NULL │ NULL           │ NULL              │       NULL │
│            1 │        9 │             11 │           12 │       NULL │ part_year=2023/part_month=2/ducklake-019abd66-7f4d-7559-8d7c-0352c4e921a2.parquet                                   │ true             │ parquet     │     55228002 │       671746996 │     1167686 │            0 │           10 │ NULL           │ NULL              │       NULL │
│            2 │       13 │             16 │           19 │       NULL │ zone_type=Municipios/source=MITMA/part_year=2023/part_month=1/ducklake-019abd69-b8a1-7702-997f-20082eb1333e.parquet │ true             │ parquet     │     55201729 │       671138942 │     1160396 │            0 │           14 │ NULL           │ NULL              │       NULL │
│            3 │       13 │             17 │           19 │       NULL │ zone_type=Municipios/source=MITMA/part_year=2023/part_month=1/ducklake-019abd6d-d935-7c48-8197-9cd631a54bf6.parquet │ true             │ parquet     │     55201729 │       670501445 │     1160522 │     55201729 │           14 │ NULL           │ NULL              │       NULL │
│            4 │       13 │             18 │           19 │       NULL │ zone_type=Municipios/source=MITMA/part_year=2023/part_month=2/ducklake-019abd71-bbc4-7a2b-9789-c815bf97d3f8.parquet │ true             │ parquet     │     55228002 │       672533285 │     1164917 │    110403458 │           14 │ NULL           │ NULL              │       NULL │
│            5 │       15 │             21 │          184 │       NULL │ zone_type=Municipios/source=MITMA/part_year=2023/part_month=2/ducklake-019abd74-27cc-7768-b9e0-1db7405e8146.parquet │ true             │ parquet     │     55228002 │       672591856 │     1155753 │            0 │           16 │ NULL           │ NULL              │       NULL │
│            6 │       15 │             22 │          184 │       NULL │ zone_type=Distritos/source=MITMA/part_year=2023/part_month=1/ducklake-019abd78-afa5-7942-b006-dfabf68623d8.parquet  │ true             │ parquet     │     88307818 │       907105962 │     1839451 │     55228002 │           16 │ NULL           │ NULL              │       NULL │
│            7 │       15 │             23 │          184 │       NULL │ zone_type=GAU/source=MITMA/part_year=2023/part_month=1/ducklake-019abfe9-90a8-7aac-b9df-63e542162f78.parquet        │ true             │ parquet     │     33343284 │       428794051 │      671877 │    143535820 │           16 │ NULL           │ NULL              │       NULL │
│            8 │       31 │             40 │           41 │       NULL │ zone_type=municiples/ducklake-019abffa-120f-7467-848e-84c33474e94e.parquet                                          │ true             │ parquet     │         2735 │        28252348 │        2092 │            0 │           32 │ NULL           │ NULL              │       NULL │
│            9 │       33 │             43 │           53 │       NULL │ zone_type=municiples/ducklake-019abffa-5338-72ea-b3b9-ec4204453125.parquet                                          │ true             │ parquet     │         2735 │        28252348 │        2092 │            0 │           34 │ NULL           │ NULL              │       NULL │
│            · │        · │              · │            · │         ·  │                           ·                                                                                         │  ·               │    ·        │           ·  │             ·   │          ·  │            · │            · │  ·             │  ·                │         ·  │
│            · │        · │              · │            · │         ·  │                           ·                                                                                         │  ·               │    ·        │           ·  │             ·   │          ·  │            · │            · │  ·             │  ·                │         ·  │
│            · │        · │              · │            · │         ·  │                           ·                                                                                         │  ·               │    ·        │           ·  │             ·   │          ·  │            · │            · │  ·             │  ·                │         ·  │
│           67 │      126 │            192 │         NULL │       NULL │ ducklake-019aca79-194a-7f64-861b-919a7cec30e1.parquet                                                               │ true             │ parquet     │        13383 │          290393 │        1526 │            0 │         NULL │ NULL           │ NULL              │       NULL │
│           68 │      127 │            194 │         NULL │       NULL │ ducklake-019aca7c-b760-7b48-90ec-1899b5ade9e4.parquet                                                               │ true             │ parquet     │     49794150 │       501579953 │      979685 │            0 │         NULL │ NULL           │ NULL              │       NULL │
│           69 │      127 │            194 │         NULL │       NULL │ ducklake-019aca80-3da6-75c8-b947-8dbe20f8b588.parquet                                                               │ true             │ parquet     │     49190188 │       494352693 │      967010 │     49794150 │         NULL │ NULL           │ NULL              │       NULL │
│           70 │      127 │            194 │         NULL │       NULL │ ducklake-019aca83-f36a-7f65-84d9-30d5f833d895.parquet                                                               │ true             │ parquet     │     26658659 │       270264752 │      535650 │     98984338 │         NULL │ NULL           │ NULL              │       NULL │
│           71 │      128 │            197 │          204 │       NULL │ zone_type=GAUS/ducklake-019acab3-d5aa-719d-8e0a-b4b8f4a89c1b.parquet                                                │ true             │ parquet     │         2203 │        18749007 │        1940 │            0 │          129 │ NULL           │ NULL              │       NULL │
│           72 │      130 │            200 │          205 │       NULL │ zone_type=municiples/ducklake-019acab3-d677-715d-8fe7-88569f5a2c79.parquet                                          │ true             │ parquet     │         2735 │        19886660 │        2036 │            0 │          131 │ NULL           │ NULL              │       NULL │
│           73 │      132 │            203 │          206 │       NULL │ zone_type=districts/ducklake-019acab3-d754-7584-91bf-272a90b14187.parquet                                           │ true             │ parquet     │         3909 │        21393518 │        2028 │            0 │          133 │ NULL           │ NULL              │       NULL │
│           74 │      134 │            209 │         NULL │       NULL │ zone_type=GAUS/ducklake-019acab5-ac39-792c-b31a-63f4293b186e.parquet                                                │ true             │ parquet     │         2203 │        18749007 │        1940 │            0 │          135 │ NULL           │ NULL              │       NULL │
│           75 │      136 │            212 │         NULL │       NULL │ zone_type=municiples/ducklake-019acab5-ad4d-7cba-bafc-cef48aa11dfb.parquet                                          │ true             │ parquet     │         2735 │        19886660 │        2036 │            0 │          137 │ NULL           │ NULL              │       NULL │
│           76 │      138 │            215 │         NULL │       NULL │ zone_type=districts/ducklake-019acab5-ae43-7fed-a326-4205d983d671.parquet                                           │ true             │ parquet     │         3909 │        21393518 │        2028 │            0 │          139 │ NULL           │ NULL              │       NULL │
├──────────────┴──────────┴────────────────┴──────────────┴────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┴─────────────┴──────────────┴─────────────────┴─────────────┴──────────────┴──────────────┴────────────────┴───────────────────┴────────────┤
│ 77 rows (20 shown)                                                                                                                                                                                                                                                                                                                              16 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
con.sql("FROM my_ducklake.snapshots();")

┌─────────────┬───────────────────────────────┬────────────────┬─────────────────────────────────────────────────────────────────┬─────────┬────────────────┬───────────────────┐
│ snapshot_id │         snapshot_time         │ schema_version │                             changes                             │ author  │ commit_message │ commit_extra_info │
│    int64    │   timestamp with time zone    │     int64      │                     map(varchar, varchar[])                     │ varchar │    varchar     │      varchar      │
├─────────────┼───────────────────────────────┼────────────────┼─────────────────────────────────────────────────────────────────┼─────────┼────────────────┼───────────────────┤
│           0 │ 2025-11-26 00:22:11.288769+01 │              0 │ {schemas_created=[main]}                                        │ NULL    │ NULL           │ NULL              │
│           1 │ 2025-11-26 00:22:14.81608+01  │              1 │ {schemas_created=[bronze]}                                      │ NULL    │ NULL           │ NULL              │
│           2 │ 2025-11-26 00:23:35.812521+01 │              2 │ {tables_created=['bronze."catalog"'], tables_inserted_into=[2]} │ NULL    │ NULL           │ NULL              │
│           3 │ 2025-11-26 00:27:17.797217+01 │              3 │ {tables_created=[bronze.od_trips]}                              │ NULL    │ NULL           │ NULL              │
│           4 │ 2025-11-26 00:27:29.328784+01 │              4 │ {tables_created=[bronze.trips]}                                 │ NULL    │ NULL           │ NULL              │
│           5 │ 2025-11-26 00:32:53.184068+01 │              5 │ {tables_created=[bronze.trips], tables_dropped=[4]}             │ NULL    │ NULL           │ NULL              │
│           6 │ 2025-11-26 00:33:08.108965+01 │              6 │ {tables_altered=[5]}                                            │ NULL    │ NULL           │ NULL              │
│           7 │ 2025-11-26 00:33:19.709915+01 │              7 │ {tables_created=[bronze.trips], tables_dropped=[5]}             │ NULL    │ NULL           │ NULL              │
│           8 │ 2025-11-26 00:33:19.722808+01 │              8 │ {tables_altered=[7]}                                            │ NULL    │ NULL           │ NULL              │
│           9 │ 2025-11-26 00:43:09.834715+01 │              9 │ {tables_created=[bronze.trips], tables_dropped=[7]}             │ NULL    │ NULL           │ NULL              │
│           · │               ·               │              · │           ·                                                     │  ·      │  ·             │  ·                │
│           · │               ·               │              · │           ·                                                     │  ·      │  ·             │  ·                │
│           · │               ·               │              · │           ·                                                     │  ·      │  ·             │  ·                │
│         206 │ 2025-11-28 14:42:57.850103+01 │            156 │ {tables_dropped=[132]}                                          │ NULL    │ NULL           │ NULL              │
│         207 │ 2025-11-28 14:44:54.872141+01 │            157 │ {tables_created=[bronze.GAUS_info]}                             │ NULL    │ NULL           │ NULL              │
│         208 │ 2025-11-28 14:44:54.899092+01 │            158 │ {tables_altered=[134]}                                          │ NULL    │ NULL           │ NULL              │
│         209 │ 2025-11-28 14:44:54.973596+01 │            158 │ {tables_inserted_into=[134]}                                    │ NULL    │ NULL           │ NULL              │
│         210 │ 2025-11-28 14:44:55.176696+01 │            159 │ {tables_created=[bronze.municiples_info]}                       │ NULL    │ NULL           │ NULL              │
│         211 │ 2025-11-28 14:44:55.185471+01 │            160 │ {tables_altered=[136]}                                          │ NULL    │ NULL           │ NULL              │
│         212 │ 2025-11-28 14:44:55.269+01    │            160 │ {tables_inserted_into=[136]}                                    │ NULL    │ NULL           │ NULL              │
│         213 │ 2025-11-28 14:44:55.458123+01 │            161 │ {tables_created=[bronze.districts_info]}                        │ NULL    │ NULL           │ NULL              │
│         214 │ 2025-11-28 14:44:55.465674+01 │            162 │ {tables_altered=[138]}                                          │ NULL    │ NULL           │ NULL              │
│         215 │ 2025-11-28 14:44:55.511055+01 │            162 │ {tables_inserted_into=[138]}                                    │ NULL    │ NULL           │ NULL              │
├─────────────┴───────────────────────────────┴────────────────┴─────────────────────────────────────────────────────────────────┴─────────┴────────────────┴───────────────────┤
│ 216 rows (20 shown)                                                                                                                                                 7 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# SILVER

In [14]:
con.sql("select * FROM bronze.trips LIMIT 10")

┌──────────┬─────────┬───────────┬────────────────┬──────────┬─────────────────┬──────────────────────┬──────────────────┬───────────────────────┬───────────┬─────────┬─────────┬─────────┬─────────┬───────────────────────┬───────────┬────────────┬───────────┬─────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────┐
│   date   │ period  │ id_origin │ id_destination │ distance │ activity_origin │ activity_destination │ study_origin_pos │ study_destination_pos │ residence │  rent   │   age   │   sex   │ n_trips │ trips_total_length_km │ part_year │ part_month │ zone_type │ source  │                                                             source_url                                                              │       ingestion_date       │
│ varchar  │ varchar │  varchar  │    varchar     │ varchar  │     varchar     │       varchar        │     varchar      │        varchar        │  varchar  │ varchar │ varchar │ varchar │ varchar │        varchar        │  varchar  │  varchar   │  varchar  │ varchar │                                                               varchar                                                               │         timestamp          │
├──────────┼─────────┼───────────┼────────────────┼──────────┼─────────────────┼──────────────────────┼──────────────────┼───────────────────────┼───────────┼─────────┼─────────┼─────────┼─────────┼───────────────────────┼───────────┼────────────┼───────────┼─────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 20230131 │ 00      │ 01001     │ 01001          │ 2-10     │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 5.739   │ 23.034                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 00      │ 01001     │ 01001          │ 2-10     │ frecuente       │ trabajo_estudio      │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 2.807   │ 10.502                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 05      │ 01001     │ 01001          │ 2-10     │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.468   │ 9.65                  │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 05      │ 01001     │ 01001          │ 2-10     │ trabajo_estudio │ frecuente            │ no               │ no                    │ 01        │ >15     │ 45-65   │ hombre  │ 2.807   │ 10.502                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 08      │ 01001     │ 01001          │ 2-10     │ casa            │ no_frecuente         │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 3.072   │ 11.34                 │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 09      │ 01001     │ 01001          │ 2-10     │ casa            │ frecuente            │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.667   │ 10.298                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 09      │ 01001     │ 01001          │ 2-10     │ casa            │ no_frecuente         │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.468   │ 9.459                 │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 09      │ 01001     │ 01001          │ 2-10     │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 6.696   │ 24.679                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 09      │ 01001     │ 01001          │ 2-10     │ no_frecuente    │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 3.072   │ 11.34                 │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
│ 20230131 │ 10      │ 01001     │ 01001          │ 2-10     │ frecuente       │ casa                 │ no               │ no                    │ 01        │ 10-15   │ NA      │ NA      │ 2.667   │ 10.298                │ 2023      │ 1          │ Distritos │ MITMA   │ https://movilidad-opendata.mitma.es/estudios_basicos/por-distritos/viajes/ficheros-diarios/2023-01/20230131_Viajes_distritos.csv.gz │ 2025-11-26 16:32:08.561373 │
├──────────┴─────────┴───────────┴────────────────┴──────────┴─────────────────┴──────────────────────┴──────────────────┴───────────────────────┴───────────┴─────────┴─────────┴─────────┴─────────┴───────────────────────┴───────────┴────────────┴───────────┴─────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────┤
│ 10 rows                                                                                                                                                                                                                                                                                                                                                                                                                           21 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [8]:
con.sql("CREATE SCHEMA IF NOT EXISTS silver")

In [8]:
con.sql("""
    CREATE OR REPLACE TABLE silver.od_metrics_daily (
        trip_date DATE,
        hour_period INTEGER,
        date TIMESTAMP,
        zone_type VARCHAR,
        id_origin VARCHAR,
        id_destination VARCHAR,
        n_trips DOUBLE,
        trips_total_length_km DOUBLE,
        origin_activity_std VARCHAR,
        destination_activity_std VARCHAR,
        residence_province_id VARCHAR,
        rent_category VARCHAR,
        age_group VARCHAR,
        sex_group VARCHAR,
        ingestion_date TIMESTAMP
    );
""")
#con.sql("ALTER TABLE silver.od_metrics_daily SET PARTITIONED BY (zone_type, trip_date);")
print("Tabla silver.od_metrics_daily creada correctamente.")

Tabla silver.od_metrics_daily creada correctamente.

In [38]:
con.sql("""
    CREATE OR REPLACE TABLE silver.od_metrics_daily (
        date TIMESTAMP,
        zone_type VARCHAR,
        distance_range_km VARCHAR,
        id_origin VARCHAR,
        id_destination VARCHAR,
        n_trips DOUBLE,
        trips_total_length_km DOUBLE,
        origin_activity_std VARCHAR,
        destination_activity_std VARCHAR,
        residence_province_id VARCHAR,
        rent_category VARCHAR,
        age_group VARCHAR,
        sex_group VARCHAR,
        ingestion_date TIMESTAMP
    );
""")
#con.sql("ALTER TABLE silver.od_metrics_daily SET PARTITIONED BY (zone_type, trip_date);")
print("Tabla silver.od_metrics_daily creada correctamente.")

Tabla silver.od_metrics_daily creada correctamente.

In [39]:
def load_silver(con, year, month, zone_type):
    print(f"Cargando Silver para {zone_type} {month}/{year}...")
    
    # Borramos datos previos de esa partición para evitar duplicados
    con.sql(f"DELETE FROM silver.od_metrics_daily WHERE zone_type = '{zone_type}' AND year(date) = {year} AND month(date) = {month}")

    query = f"""--sql
    INSERT INTO silver.od_metrics_daily
    SELECT 
        --strptime(date, '%Y%m%d') as trip_date,
        --TRY_CAST(period AS INTEGER) as hour_period,
        try_strptime(date::VARCHAR || LPAD(period::VARCHAR, 2, '0'), '%Y%m%d%H') as date, -- Join date and hour in a TIMESTAMP
        zone_type,
        distance,
        TRIM(id_origin), -- TRIM for spaces in ids
        TRIM(id_destination),
        
        -- Limpieza numérica robusta
        ROUND(TRY_CAST(n_trips AS DOUBLE), 1) as n_trips,
        ROUND(TRY_CAST(trips_total_length_km AS DOUBLE), 3) as trips_total_length_km,
        --TRY_CAST(REPLACE(REPLACE(n_trips, '.', ''), ',', '.') AS DOUBLE) as n_trips,
        --TRY_CAST(REPLACE(REPLACE(trips_total_length_km, '.', ''), ',', '.') AS DOUBLE) as trips_total_length_km,

        CASE WHEN activity_origin = 'casa' THEN 'Home' WHEN activity_origin = 'trabajo_estudio' THEN 'Work_Study'  
            WHEN activity_origin ='frecuente' THEN 'frequent'  ELSE 'not_frequent' END,

        CASE WHEN activity_destination = 'casa' THEN 'Home' WHEN activity_destination = 'trabajo_estudio' THEN 'Work_Study'  
            WHEN activity_destination ='frecuente' THEN 'frequent'  ELSE 'not_frequent' END,
            
        SUBSTR(residence, 1, 2),
        NULLIF(rent, 'NA'),
        NULLIF(age, 'NA'),
        NULLIF(sex, 'NA'),
        current_timestamp AS ingestion_date

    FROM bronze.trips
    WHERE 
        -- FILTROS NUMÉRICOS (Ignoran ceros a la izquierda o espacios)
        TRY_CAST(part_year AS INTEGER) = {year}
        AND TRY_CAST(part_month AS INTEGER) = {month}
        AND TRIM(zone_type) = '{zone_type}' LIMIT 50
    """
    con.sql(query)

In [40]:
# Ejecutamos
load_silver(con, 2023, 2, "Distritos")

Cargando Silver para Distritos 2/2023...

In [41]:
# VERIFICACIÓN de la carga de datos en silver
con.sql("SELECT COUNT(*) as filas_insertadas FROM silver.od_metrics_daily").show()
con.sql("SELECT * FROM silver.od_metrics_daily " )

┌──────────────────┐
│ filas_insertadas │
│      int64       │
├──────────────────┤
│               50 │
└──────────────────┘

┌─────────────────────┬───────────┬───────────────────┬───────────┬────────────────┬─────────┬───────────────────────┬─────────────────────┬──────────────────────────┬───────────────────────┬───────────────┬───────────┬───────────┬────────────────────────────┐
│        date         │ zone_type │ distance_range_km │ id_origin │ id_destination │ n_trips │ trips_total_length_km │ origin_activity_std │ destination_activity_std │ residence_province_id │ rent_category │ age_group │ sex_group │       ingestion_date       │
│      timestamp      │  varchar  │      varchar      │  varchar  │    varchar     │ double  │        double         │       varchar       │         varchar          │        varchar        │    varchar    │  varchar  │  varchar  │         timestamp          │
├─────────────────────┼───────────┼───────────────────┼───────────┼────────────────┼─────────┼───────────────────────┼─────────────────────┼──────────────────────────┼───────────────────────┼───────────────┼───────────┼───────────┼────────────────────────────┤
│ 2023-02-28 06:00:00 │ Distritos │ 0.5-2             │ 01009_AM  │ 01001          │     2.9 │                 3.018 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 09:00:00 │ Distritos │ 0.5-2             │ 01009_AM  │ 01001          │     2.3 │                 2.609 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 19:00:00 │ Distritos │ 0.5-2             │ 01009_AM  │ 01001          │     2.3 │                 2.609 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 22:00:00 │ Distritos │ 0.5-2             │ 01009_AM  │ 01001          │     2.5 │                 3.114 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 21:00:00 │ Distritos │ 10-50             │ 01002     │ 01001          │     2.5 │               115.606 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 08:00:00 │ Distritos │ 10-50             │ 01009_AM  │ 01001          │     2.9 │                29.975 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 11:00:00 │ Distritos │ 10-50             │ 01009_AM  │ 01001          │     3.2 │                37.143 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 14:00:00 │ Distritos │ 10-50             │ 01009_AM  │ 01001          │     3.2 │                48.099 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 19:00:00 │ Distritos │ 10-50             │ 01009_AM  │ 01001          │     2.9 │                45.975 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 17:00:00 │ Distritos │ 10-50             │ 01017_AM  │ 01001          │     2.5 │                26.409 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│          ·          │     ·     │   ·               │    ·      │   ·            │      ·  │                   ·   │    ·                │  ·                       │ ·                     │   ·           │  ·        │  ·        │             ·              │
│          ·          │     ·     │   ·               │    ·      │   ·            │      ·  │                   ·   │    ·                │  ·                       │ ·                     │   ·           │  ·        │  ·        │             ·              │
│          ·          │     ·     │   ·               │    ·      │   ·            │      ·  │                   ·   │    ·                │  ·                       │ ·                     │   ·           │  ·        │  ·        │             ·              │
│ 2023-02-28 16:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     3.2 │                45.795 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 17:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     7.7 │               104.054 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 18:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     9.6 │               141.599 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 19:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     8.1 │               114.409 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 20:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │    12.9 │                178.98 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 21:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     3.2 │                43.934 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 22:00:00 │ Distritos │ 10-50             │ 0105902   │ 01001          │     4.8 │                63.904 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 08:00:00 │ Distritos │ 10-50             │ 0105903   │ 01001          │     2.9 │                32.548 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 09:00:00 │ Distritos │ 10-50             │ 0105903   │ 01001          │     2.3 │                26.336 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
│ 2023-02-28 10:00:00 │ Distritos │ 10-50             │ 0105903   │ 01001          │     2.9 │                36.982 │ frequent            │ Home                     │ 01                    │ 10-15         │ NULL      │ NULL      │ 2025-11-29 12:38:18.948817 │
├─────────────────────┴───────────┴───────────────────┴───────────┴────────────────┴─────────┴───────────────────────┴─────────────────────┴──────────────────────────┴───────────────────────┴───────────────┴───────────┴───────────┴────────────────────────────┤
│ 50 rows (20 shown)                                                                                                                                                                                                                                    14 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [26]:
# VERIFICACIÓN de la carga de datos en silver
con.sql("SELECT COUNT(*) as filas_insertadas FROM silver.od_metrics_daily").show()
con.sql("SELECT * FROM silver.od_metrics_daily WHERE DAY(trip_date) = 1 AND hour_period = 8 AND id_origin = '0105903' --AND id_destination = '42025_AM'ORDER BY id_destination DESC" )

┌──────────────────┐
│ filas_insertadas │
│      int64       │
├──────────────────┤
│               50 │
└──────────────────┘

BinderException: Binder Error: Referenced column "trip_date" not found in FROM clause!
Candidate bindings: "trips_total_length_km", "rent_category", "n_trips", "id_destination", "ingestion_date"

In [10]:
import duckdb

def cargar_renta_ine(con, url, year, zone_type='Distritos'):
    """
    Carga datos brutos del INE (Renta) directamente desde URL al DuckLake.
    """
    print(f"--- Cargando Renta INE ({year}) al Bronze Layer ---")
    
    # 1. Configuración específica para el INE
    # El INE suele usar ';' como separador y a veces codificación Latin-1
    try:
        query = f"""
                SELECT 
                    -- Leemos todo como VARCHAR en Bronze para no fallar
                    count(*)
                    
                   
                    
                FROM read_csv(
                    '{url}', 
                    delim=';',          -- Separador típico del INE
                    header=True, 
                    auto_detect=True,   -- DuckDB suele detectar bien Latin-1 vs UTF-8
                    all_varchar=True,   -- Seguridad máxima para Bronze
                    ignore_errors=True,
                    null_padding=True
                )
            
        """
        
        con.sql(query).show()
        print(f"🚀 Datos de Renta del INE ({year}) cargados exitosamente.")
        
    except Exception as e:
        print(f"❌ Error cargando INE: {e}")

# --- EJECUCIÓN ---
con = duckdb.connect('movilidad_datalake.duckdb')
con.sql("INSTALL httpfs; LOAD httpfs;")

# URL de ejemplo (Renta media por hogar por distritos/secciones - Formato CSV INE)
# Nota: Debes buscar la URL exacta del año que quieras en la web del INE > Atlas de Renta
url_ine_renta_2021 = "https://www.ine.es/jaxiT3/files/t/es/csv_bd/30656.csv?nocab=1" 

cargar_renta_ine(con, url_ine_renta_2021, 2021)

con.close()

--- Cargando Renta INE (2021) al Bronze Layer ---
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│        27810 │
└──────────────┘

🚀 Datos de Renta del INE (2021) cargados exitosamente.

In [ ]:
import requests
import pandas as pd
from pyjstat import pyjstat

# 1. Configuración
# ID de ejemplo para Renta Media por hogar por Distritos (Verifica el ID actual en la web del INE)
# A fecha de hoy, un ID común para renta por distritos suele rondar los 30xxx o 37xxx
TABLE_ID = "30656"  # ESTE ES UN EJEMPLO, debes buscar el ID exacto que necesitas en la web
BASE_URL = f"https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/{TABLE_ID}?tip=AM"


# 2. Hacemos la petición
try:
    # request json file of the table 
    response = requests.get(BASE_URL)
    response.raise_for_status()
    resultados = []
    # print(type(response.json()))
    for entrada in response.json():
        # Filtro: Solo Distritos

        es_distrito = False
        codigo_distrito = "N/A"
        nombre_distrito = "N/A"
        
        #Test metadata is not empty
        metadata = entrada.get("MetaData", [])
        if metadata is None: continue
        for meta in entrada.get("MetaData", []):
            if meta.get("T3_Variable") == "Distritos":
                es_distrito = True
                codigo_distrito = meta.get("Codigo")
                nombre_distrito = meta.get("Nombre")
                break
        
        if not es_distrito:
            continue

        # Limpieza del nombre del concepto
        nombre_completo = entrada.get("Nombre", "")
        try:
            concepto = nombre_completo.split('.')[-2].strip()
        except:
            concepto = nombre_completo

        # Filtro de Años
        for dato in entrada.get("Data", []):
            anyo = dato.get("Anyo")
            if 2022 <= anyo <= 2025:
                resultados.append({
                    "ine_id_district": codigo_distrito,
                    "name": nombre_distrito,
                    "Concepto": concepto,
                    "Año": anyo,
                    "Valor": dato.get("Valor")
                })


    df = pd.DataFrame(resultados)

    df_pivot = df.pivot_table(
                index=['Codigo', 'Nombre', 'Concepto'],
                columns='Año',
                values='Valor'
            ).reset_index()
except Exception as e:
    print(f"Error: {e}")

Error: 'Codigo'

In [51]:
df_pivot.head(50)

Año,Codigo,Nombre,Concepto,2022,2023
0,0200101,Abengibre distrito 01,Media de la renta por unidad de consumo,19598.0,20666.0
1,0200101,Abengibre distrito 01,Mediana de la renta por unidad de consumo,17150.0,18200.0
2,0200101,Abengibre distrito 01,Renta bruta media por hogar,37804.0,40010.0
3,0200101,Abengibre distrito 01,Renta bruta media por persona,15122.0,16478.0
4,0200101,Abengibre distrito 01,Renta neta media por hogar,32657.0,34249.0
5,0200101,Abengibre distrito 01,Renta neta media por persona,13063.0,14105.0
6,0200201,Alatoz distrito 01,Media de la renta por unidad de consumo,15925.0,17008.0
7,0200201,Alatoz distrito 01,Mediana de la renta por unidad de consumo,15050.0,15750.0
8,0200201,Alatoz distrito 01,Renta bruta media por hogar,27007.0,29229.0
9,0200201,Alatoz distrito 01,Renta bruta media por persona,12607.0,13765.0
10,0200201,Alatoz distrito 01,Renta neta media por hogar,24306.0,25953.0
11,0200201,Alatoz distrito 01,Renta neta media por persona,11346.0,12222.0
12,0200301,Albacete distrito 01,Media de la renta por unidad de consumo,23008.0,24084.0
13,0200301,Albacete distrito 01,Mediana de la renta por unidad de consumo,20650.0,21350.0
14,0200301,Albacete distrito 01,Renta bruta media por hogar,47553.0,50158.0
15,0200301,Albacete distrito 01,Renta bruta media por persona,19284.0,20451.0
16,0200301,Albacete distrito 01,Renta neta media por hogar,38456.0,40135.0
17,0200301,Albacete distrito 01,Renta neta media por persona,15595.0,16364.0
18,0200302,Albacete distrito 02,Media de la renta por unidad de consumo,19735.0,20633.0
19,0200302,Albacete distrito 02,Mediana de la renta por unidad de consumo,17850.0,19250.0
20,0200302,Albacete distrito 02,Renta bruta media por hogar,41117.0,43256.0
21,0200302,Albacete distrito 02,Renta bruta media por persona,15716.0,16651.0
22,0200302,Albacete distrito 02,Renta neta media por hogar,34209.0,35776.0
23,0200302,Albacete distrito 02,Renta neta media por persona,13076.0,13772.0
24,0200303,Albacete distrito 03,Media de la renta por unidad de consumo,18678.0,19427.0
25,0200303,Albacete distrito 03,Mediana de la renta por unidad de consumo,16450.0,17150.0
26,0200303,Albacete distrito 03,Renta bruta media por hogar,38206.0,39952.0
27,0200303,Albacete distrito 03,Renta bruta media por persona,14950.0,15757.0
28,0200303,Albacete distrito 03,Renta neta media por hogar,32129.0,33453.0
29,0200303,Albacete distrito 03,Renta neta media por persona,12572.0,13194.0
30,0200304,Albacete distrito 04,Media de la renta por unidad de consumo,18630.0,19485.0
31,0200304,Albacete distrito 04,Mediana de la renta por unidad de consumo,16450.0,17850.0
32,0200304,Albacete distrito 04,Renta bruta media por hogar,38846.0,40956.0
33,0200304,Albacete distrito 04,Renta bruta media por persona,14762.0,15632.0
34,0200304,Albacete distrito 04,Renta neta media por hogar,32584.0,34222.0
35,0200304,Albacete distrito 04,Renta neta media por persona,12382.0,13062.0
36,0200305,Albacete distrito 05,Media de la renta por unidad de consumo,18753.0,19658.0
37,0200305,Albacete distrito 05,Mediana de la renta por unidad de consumo,16450.0,17150.0
38,0200305,Albacete distrito 05,Renta bruta media por hogar,38061.0,40444.0
39,0200305,Albacete distrito 05,Renta bruta media por persona,15236.0,16105.0
40,0200305,Albacete distrito 05,Renta neta media por hogar,31742.0,33713.0
41,0200305,Albacete distrito 05,Renta neta media por persona,12706.0,13424.0
42,0200306,Albacete distrito 06,Media de la renta por unidad de consumo,27871.0,29078.0
43,0200306,Albacete distrito 06,Mediana de la renta por unidad de consumo,24850.0,25550.0
44,0200306,Albacete distrito 06,Renta bruta media por hogar,59616.0,62911.0
45,0200306,Albacete distrito 06,Renta bruta media por persona,23600.0,25110.0
46,0200306,Albacete distrito 06,Renta neta media por hogar,46746.0,48968.0
47,0200306,Albacete distrito 06,Renta neta media por persona,18505.0,19545.0
48,0200307,Albacete distrito 07,Media de la renta por unidad de consumo,20179.0,21293.0
49,0200307,Albacete distrito 07,Mediana de la renta por unidad de consumo,17850.0,18550.0